[build]
# This forces the builder to manually download Node.js and PNPM into the isolated container
providers = ["node"]
builder = "nixpacks"

[phases.install]
# Force the container to fetch pnpm before doing anything else
cmds = ["corepack enable", "pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm build"]

[deploy]
startCommand = "pnpm start"
restartPolicy = "on-failure"
